# Generated by Django 5.0.2 on 2025-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Property Owner')], default='tenant', max_length=10),
        ),
    ]
