# Generated by Django 5.0.2 on 2025-06-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.AddField(
            model_name='property',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Standard terms and conditions for renting this property', null=True),
        ),
    ]
